/**
 * Bulk Contact Form Outreach System — Sample Lead Templates & Pre-loaded Datasets
 * Fully configured with the 12 standard lead fields:
 * First Name, Last Name, Title, Company Name, Email, Industry, Person Linkedin Url,
 * Website, Company Linkedin Url, City, State, Country.
 */

export interface SampleDataset {
  id: string;
  name: string;
  category: string;
  description: string;
  leadCount: number;
  headers: string[];
  rows: Array<Record<string, string>>;
}

export const SAMPLE_HEADERS_12 = [
  'First Name',
  'Last Name',
  'Title',
  'Company Name',
  'Email',
  'Industry',
  'Person Linkedin Url',
  'Website',
  'Company Linkedin Url',
  'City',
  'State',
  'Country',
  'Personalized Opening Line',
  'Problem Paragraph',
  'Pitch',
  'CTA',
];

export const SAMPLE_DATASETS: SampleDataset[] = [
  {
    id: 'b2b-saas',
    name: 'B2B SaaS & Tech Companies',
    category: 'Software & Tech',
    description: 'High-growth technology leaders with verified contact pages, titles, and LinkedIn profiles.',
    leadCount: 10,
    headers: SAMPLE_HEADERS_12,
    rows: [
      {
        'First Name': 'Sarah',
        'Last Name': 'Connor',
        Title: 'Chief Technology Officer',
        'Company Name': 'Acme Cloud Dynamics',
        Email: 'sarah@acmeclouddynamics.com',
        Industry: 'Cloud Infrastructure',
        'Person Linkedin Url': 'https://linkedin.com/in/sarah-connor-cto',
        Website: 'https://acmeclouddynamics.com',
        'Company Linkedin Url': 'https://linkedin.com/company/acme-cloud-dynamics',
        City: 'San Francisco',
        State: 'California',
        Country: 'United States',
        'Personalized Opening Line': 'Loved your recent talk on multi-region AWS cloud latency reduction.',
        'Problem Paragraph': 'Most growing engineering teams struggle with manual pipeline bottlenecks and unmonitored infrastructure sprawl.',
        Pitch: 'Our platform automates your multi-region failover and trims AWS compute spend by 35% within 14 days.',
        CTA: 'Would you be open to a 10-minute technical walkthrough this Thursday?',
      },
      {
        'First Name': 'Alex',
        'Last Name': 'Rivers',
        Title: 'VP of Product Engineering',
        'Company Name': 'Nexus AI Solutions',
        Email: 'alex@nexuslogistics.io',
        Industry: 'Artificial Intelligence',
        'Person Linkedin Url': 'https://linkedin.com/in/alex-rivers-ai',
        Website: 'https://nexuslogistics.io',
        'Company Linkedin Url': 'https://linkedin.com/company/nexus-ai-solutions',
        City: 'Austin',
        State: 'Texas',
        Country: 'United States',
        'Personalized Opening Line': 'Congratulations on your Series A milestone and rapid customer adoption in Texas!',
        'Problem Paragraph': 'Scaling real-time AI model inferencing often leads to unpredictable GPU cost spikes and throughput throttling.',
        Pitch: 'We provide dynamic GPU load-balancing that cuts inference latency in half without extra hardware.',
        CTA: 'Can I send over a 2-page benchmark comparison tailored to your stack?',
      },
      {
        'First Name': 'Oliver',
        'Last Name': 'Smith',
        Title: 'Head of Operations',
        'Company Name': 'CloudScale Global Ltd',
        Email: 'oliver@cloudscaleuk.co.uk',
        Industry: 'DevOps & Tooling',
        'Person Linkedin Url': 'https://linkedin.com/in/oliver-smith-ops',
        Website: 'https://cloudscaleuk.co.uk',
        'Company Linkedin Url': 'https://linkedin.com/company/cloudscale-global',
        City: 'London',
        State: 'Greater London',
        Country: 'United Kingdom',
      },
      {
        'First Name': 'Elena',
        'Last Name': 'Rostova',
        Title: 'Chief Information Security Officer',
        'Company Name': 'Vanguard Cyber Security',
        Email: 'elena@vanguardsec.com',
        Industry: 'Cybersecurity',
        'Person Linkedin Url': 'https://linkedin.com/in/elena-rostova-security',
        Website: 'https://vanguardsec.com',
        'Company Linkedin Url': 'https://linkedin.com/company/vanguard-cyber-security',
        City: 'Berlin',
        State: 'Berlin',
        Country: 'Germany',
      },
      {
        'First Name': 'David',
        'Last Name': 'Kim',
        Title: 'Director of Growth',
        'Company Name': 'PulseMetrics Analytics',
        Email: 'david@pulsemetrics.net',
        Industry: 'Product Analytics',
        'Person Linkedin Url': 'https://linkedin.com/in/david-kim-growth',
        Website: 'https://pulsemetrics.net',
        'Company Linkedin Url': 'https://linkedin.com/company/pulsemetrics-analytics',
        City: 'Seattle',
        State: 'Washington',
        Country: 'United States',
      },
      {
        'First Name': 'Maya',
        'Last Name': 'Patel',
        Title: 'Co-Founder & CEO',
        'Company Name': 'Aetheria Digital Cloud',
        Email: 'maya@aetheriadigital.io',
        Industry: 'Cloud SaaS',
        'Person Linkedin Url': 'https://linkedin.com/in/maya-patel-ceo',
        Website: 'https://aetheriadigital.io',
        'Company Linkedin Url': 'https://linkedin.com/company/aetheria-digital',
        City: 'Toronto',
        State: 'Ontario',
        Country: 'Canada',
      },
      {
        'First Name': 'Marcus',
        'Last Name': 'Vance',
        Title: 'Managing Director',
        'Company Name': 'Synthetix Logic Systems',
        Email: 'marcus@synthetixlogic.com',
        Industry: 'Enterprise Software',
        'Person Linkedin Url': 'https://linkedin.com/in/marcus-vance-md',
        Website: 'https://synthetixlogic.com',
        'Company Linkedin Url': 'https://linkedin.com/company/synthetix-logic',
        City: 'Sydney',
        State: 'New South Wales',
        Country: 'Australia',
      },
      {
        'First Name': 'Astrid',
        'Last Name': 'Lindgren',
        Title: 'Head of Partnerships',
        'Company Name': 'Nordic Scale Labs',
        Email: 'astrid@nordicscalelabs.se',
        Industry: 'FinTech',
        'Person Linkedin Url': 'https://linkedin.com/in/astrid-lindgren-fintech',
        Website: 'https://nordicscalelabs.se',
        'Company Linkedin Url': 'https://linkedin.com/company/nordic-scale-labs',
        City: 'Stockholm',
        State: 'Stockholm',
        Country: 'Sweden',
      },
      {
        'First Name': 'Jason',
        'Last Name': 'Hayes',
        Title: 'VP of Sales',
        'Company Name': 'HyperFlow Automation',
        Email: 'jason@hyperflowauto.com',
        Industry: 'Workflow Automation',
        'Person Linkedin Url': 'https://linkedin.com/in/jason-hayes-sales',
        Website: 'https://hyperflowauto.com',
        'Company Linkedin Url': 'https://linkedin.com/company/hyperflow-automation',
        City: 'New York',
        State: 'New York',
        Country: 'United States',
      },
      {
        'First Name': 'Liam',
        'Last Name': 'Chen',
        Title: 'Chief Revenue Officer',
        'Company Name': 'ZetaByte Data Systems',
        Email: 'liam@zetabytedata.com',
        Industry: 'Big Data & ML',
        'Person Linkedin Url': 'https://linkedin.com/in/liam-chen-cro',
        Website: 'https://zetabytedata.com',
        'Company Linkedin Url': 'https://linkedin.com/company/zetabyte-data',
        City: 'Singapore',
        State: 'Central Region',
        Country: 'Singapore',
      },
    ],
  },
  {
    id: 'ecommerce',
    name: 'E-Commerce Brands & Retailers',
    category: 'Retail & Brands',
    description: 'Online consumer brand founders, CEOs, and marketing directors.',
    leadCount: 5,
    headers: SAMPLE_HEADERS_12,
    rows: [
      {
        'First Name': 'Chloe',
        'Last Name': 'Bennett',
        Title: 'Founder & Brand Director',
        'Company Name': 'Lumina Lifestyle Gear',
        Email: 'chloe@luminalifestyle.com',
        Industry: 'Apparel & Fashion',
        'Person Linkedin Url': 'https://linkedin.com/in/chloe-bennett-fashion',
        Website: 'https://luminalifestyle.com',
        'Company Linkedin Url': 'https://linkedin.com/company/lumina-lifestyle',
        City: 'Los Angeles',
        State: 'California',
        Country: 'United States',
      },
      {
        'First Name': 'Marcus',
        'Last Name': 'Holloway',
        Title: 'Head of E-Commerce',
        'Company Name': 'Apex Artisan Coffee Co',
        Email: 'marcus@apexartisancoffee.com',
        Industry: 'Food & Beverage',
        'Person Linkedin Url': 'https://linkedin.com/in/marcus-holloway-ecom',
        Website: 'https://apexartisancoffee.com',
        'Company Linkedin Url': 'https://linkedin.com/company/apex-artisan-coffee',
        City: 'Portland',
        State: 'Oregon',
        Country: 'United States',
      },
      {
        'First Name': 'Matteo',
        'Last Name': 'Rossi',
        Title: 'Chief Marketing Officer',
        'Company Name': 'Velocita Sports Goods',
        Email: 'matteo@velocitasports.it',
        Industry: 'Fitness & Sports',
        'Person Linkedin Url': 'https://linkedin.com/in/matteo-rossi-cmo',
        Website: 'https://velocitasports.it',
        'Company Linkedin Url': 'https://linkedin.com/company/velocita-sports',
        City: 'Milan',
        State: 'Lombardy',
        Country: 'Italy',
      },
      {
        'First Name': 'Sophia',
        'Last Name': 'Taylor',
        Title: 'E-Commerce Marketing Lead',
        'Company Name': 'Zenith Home & Living',
        Email: 'sophia@zenithhomedecor.com',
        Industry: 'Home Furnishings',
        'Person Linkedin Url': 'https://linkedin.com/in/sophia-taylor-decor',
        Website: 'https://zenithhomedecor.com',
        'Company Linkedin Url': 'https://linkedin.com/company/zenith-home',
        City: 'Chicago',
        State: 'Illinois',
        Country: 'United States',
      },
      {
        'First Name': 'Emma',
        'Last Name': 'Watson',
        Title: 'Head of Digital Growth',
        'Company Name': 'PureGlow Organics',
        Email: 'emma@puregloworganics.co.uk',
        Industry: 'Beauty & Skincare',
        'Person Linkedin Url': 'https://linkedin.com/in/emma-watson-growth',
        Website: 'https://puregloworganics.co.uk',
        'Company Linkedin Url': 'https://linkedin.com/company/pureglow-organics',
        City: 'London',
        State: 'Greater London',
        Country: 'United Kingdom',
      },
    ],
  },
  {
    id: 'agencies',
    name: 'Digital & Growth Agencies',
    category: 'Marketing & Media',
    description: 'Agency founders, Managing Partners, and Business Development Leads.',
    leadCount: 5,
    headers: SAMPLE_HEADERS_12,
    rows: [
      {
        'First Name': 'Daniel',
        'Last Name': 'Craig',
        Title: 'Managing Partner',
        'Company Name': 'Elevate Growth Partners',
        Email: 'daniel@elevategrowthagency.com',
        Industry: 'Growth Marketing',
        'Person Linkedin Url': 'https://linkedin.com/in/daniel-craig-growth',
        Website: 'https://elevategrowthagency.com',
        'Company Linkedin Url': 'https://linkedin.com/company/elevate-growth-partners',
        City: 'Miami',
        State: 'Florida',
        Country: 'United States',
      },
      {
        'First Name': 'Zoe',
        'Last Name': 'Kravitz',
        Title: 'Creative Director',
        'Company Name': 'PixelCraft Design Studio',
        Email: 'zoe@pixelcraftstudio.io',
        Industry: 'UI/UX & Branding',
        'Person Linkedin Url': 'https://linkedin.com/in/zoe-kravitz-design',
        Website: 'https://pixelcraftstudio.io',
        'Company Linkedin Url': 'https://linkedin.com/company/pixelcraft-studio',
        City: 'San Francisco',
        State: 'California',
        Country: 'United States',
      },
      {
        'First Name': 'Nathan',
        'Last Name': 'Drake',
        Title: 'Head of SEO Strategy',
        'Company Name': 'RankVelocity SEO Group',
        Email: 'nathan@rankvelocityseo.com',
        Industry: 'SEO & Organic Growth',
        'Person Linkedin Url': 'https://linkedin.com/in/nathan-drake-seo',
        Website: 'https://rankvelocityseo.com',
        'Company Linkedin Url': 'https://linkedin.com/company/rankvelocity-seo',
        City: 'Dallas',
        State: 'Texas',
        Country: 'United States',
      },
      {
        'First Name': 'James',
        'Last Name': 'Bond',
        Title: 'VP of Business Development',
        'Company Name': 'Apex Media Solutions',
        Email: 'james@apexmediaglobal.co.uk',
        Industry: 'Digital Advertising',
        'Person Linkedin Url': 'https://linkedin.com/in/james-bond-media',
        Website: 'https://apexmediaglobal.co.uk',
        'Company Linkedin Url': 'https://linkedin.com/company/apex-media-solutions',
        City: 'Manchester',
        State: 'Greater Manchester',
        Country: 'United Kingdom',
      },
      {
        'First Name': 'Hannah',
        'Last Name': 'Abbott',
        Title: 'Founder & Technical Lead',
        'Company Name': 'Verve Interactive Labs',
        Email: 'hannah@verveinteractivelabs.com',
        Industry: 'Web Engineering',
        'Person Linkedin Url': 'https://linkedin.com/in/hannah-abbott-labs',
        Website: 'https://verveinteractivelabs.com',
        'Company Linkedin Url': 'https://linkedin.com/company/verve-interactive-labs',
        City: 'Boston',
        State: 'Massachusetts',
        Country: 'United States',
      },
    ],
  },
];

/**
 * Generates and triggers a browser file download for a sample CSV.
 */
export function downloadSampleCsv(datasetId: string = 'b2b-saas'): void {
  const dataset = SAMPLE_DATASETS.find((d) => d.id === datasetId) || SAMPLE_DATASETS[0];

  const headerLine = dataset.headers.map((h) => `"${h.replace(/"/g, '""')}"`).join(',');
  const rowLines = dataset.rows.map((row) =>
    dataset.headers.map((h) => `"${(row[h] || '').replace(/"/g, '""')}"`).join(',')
  );

  const csvContent = [headerLine, ...rowLines].join('\r\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `${dataset.id}_sample_leads.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
