import Link from 'next/link';
import {
  ArrowRight, BarChart3, Bot, Building2, CheckCircle2, ChevronRight, ClipboardCheck,
  FileSearch, Gauge, Globe2, Layers3, ListChecks, Mail, Megaphone, MousePointerClick,
  Search, Send, Sparkles, Target, Users, Workflow, Zap,
} from 'lucide-react';
import { LandingHeader } from '@/components/layout/LandingHeader';
import { LandingFooter } from '@/components/layout/LandingFooter';

const benefits = [
  [Globe2, 'Direct Website Outreach', 'Send outreach through a target company’s website contact form instead of relying entirely on traditional email outreach.'],
  [Sparkles, 'AI-Personalized Messages', 'Create relevant messages using available prospect and company information instead of sending the same generic message to every lead.'],
  [Zap, 'Scale Your Outreach', 'Process prospect lists through one centralized campaign workflow instead of opening and completing every website form manually.'],
  [Mail, 'Less Email Infrastructure', 'Reduce dependence on maintaining multiple cold-email sending domains and mailboxes with a website-based outreach channel.'],
  [Layers3, 'One Centralized Workspace', 'Manage leads, contact-form discovery, AI personalization, campaigns, submissions, and results from one workspace.'],
  [BarChart3, 'Track Your Outreach', 'Monitor campaign progress, submission status, successful submissions, failures, and review-required outcomes.'],
] as const;

const workflow = [
  [ListChecks, 'Upload Leads', 'Import your prospect and company list.'], [Search, 'Find Contact Forms', 'Identify relevant forms on target websites.'],
  [Bot, 'AI Personalize', 'Generate a tailored message for each prospect.'], [Send, 'Submit', 'Send through the website contact workflow.'],
  [ClipboardCheck, 'Track Results', 'Review progress and submission outcomes.'],
] as const;

const audiences = [
  [Building2, 'B2B Agencies', 'Coordinate multiple client outreach campaigns, lead lists, and results from one organized workflow.'],
  [Users, 'Sales Teams', 'Add website contact forms as a structured channel alongside your existing prospecting process.'],
  [Target, 'Lead Generation Specialists', 'Turn company and website lists into personalized, trackable contact-form campaigns.'],
  [Megaphone, 'Growth & Marketing Teams', 'Test relevant website outreach messages while keeping campaign activity visible and reviewable.'],
] as const;

export default function BenefitsPage() {
  return <div className="min-h-screen bg-[#f4f8fd] text-slate-950"><LandingHeader /><main>
    <section className="px-4 py-8 sm:px-6 lg:py-12"><div className="mx-auto grid max-w-7xl items-center gap-10 overflow-hidden rounded-[2.25rem] border border-blue-100 bg-white p-7 shadow-sm sm:p-10 lg:grid-cols-[1.02fr_.98fr] lg:p-14"><div><Pill>Why ContactReachout?</Pill><h1 className="mt-6 text-4xl font-black leading-[1.06] tracking-tight sm:text-5xl lg:text-6xl">Reach more prospects through <span className="text-[#0e6de4]">website contact forms.</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-slate-600">Combine bulk contact-form submission, AI personalization, contact-form discovery, campaign management, and submission tracking in one scalable workspace.</p><div className="mt-8 flex flex-wrap gap-3"><Primary href="/signup">Start Free</Primary><Secondary href="#workflow">See How It Works</Secondary></div></div><CampaignMockup /></div></section>

    <Section eyebrow="Benefits overview" title="Built for Smarter Website Outreach" subtitle="A focused workflow for moving from prospect data to relevant, reviewable website outreach."><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{benefits.map(([Icon,title,text])=><FeatureCard key={title} icon={Icon} title={title} text={text}/>)}</div></Section>

    <section id="workflow"><Section eyebrow="How it works" title="From Lead List to Website Outreach" subtitle="Five connected steps keep discovery, personalization, submission, and reporting easy to follow."><div className="grid gap-3 lg:grid-cols-5">{workflow.map(([Icon,title,text],index)=><div key={title} className="relative rounded-3xl border border-blue-100 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-50 text-[#0e6de4]"><Icon className="h-5 w-5"/></span><span className="text-xs font-black text-blue-300">0{index+1}</span></div><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p>{index<4&&<ChevronRight className="absolute -right-4 top-1/2 z-10 hidden h-5 w-5 text-blue-400 lg:block"/>}</div>)}</div></Section></section>

    <Section eyebrow="AI personalization" title="Relevant messages, without the generic feel" subtitle="Use prospect and company context to create a stronger starting point, then review and edit before submission."><div className="grid gap-5 lg:grid-cols-2"><MessageCard label="BEFORE" title="Generic Outreach" text="Hi, we offer digital marketing services and would love to work with your company. Please let us know if you are interested."/><MessageCard featured label="AFTER" title="AI-Personalized Outreach" text="Hi {{First Name}}, I noticed that {{Company}} focuses on {{Industry/Service}}. We help companies like yours improve their online visibility and generate more qualified opportunities. I’d be happy to share a few ideas specifically for {{Company}}."/></div></Section>

    <Section eyebrow="Channel comparison" title="A Different Way to Reach Prospects" subtitle="ContactReachout adds a website-based outreach workflow without making absolute claims about delivery or replies."><ComparisonTable /></Section>

    <Section eyebrow="Infrastructure" title="Reduce Dependence on Traditional Email Infrastructure" subtitle="A more direct operational path centered on company websites and their available contact workflows."><div className="grid gap-5 lg:grid-cols-2"><FlowCard title="Traditional Cold Email" icon={Mail} items={['Domains','Mailboxes','Authentication','Warm-up','Sending','Inbox / Promotions / Spam']}/><FlowCard featured title="ContactReachout" icon={Globe2} items={['Lead List','Find Website Contact Form','AI Personalize','Submit','Track']}/></div></Section>

    <section className="px-4 py-8 sm:px-6"><div className="mx-auto max-w-7xl rounded-[2.25rem] bg-[#0e6de4] p-7 text-white shadow-xl shadow-blue-200/60 sm:p-10 lg:p-14"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-100">Scale with control</p><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">Turn Manual Website Outreach Into a Scalable Workflow</h2><p className="mt-5 leading-7 text-blue-100">Keep the key stages connected while preserving review points and campaign visibility.</p></div><div className="rounded-3xl bg-white/10 p-5 ring-1 ring-white/20"><div className="grid gap-3 sm:grid-cols-5">{['Lead List','Forms Found','AI Messages','Submissions','Results'].map((item,index)=><div key={item} className="rounded-2xl bg-white p-4 text-center text-sm font-black text-slate-900"><span className="block text-xs text-[#0e6de4]">0{index+1}</span>{item}</div>)}</div></div></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['Work From One Campaign','Personalize at Scale','Track Every Submission','Reduce Manual Work'].map(text=><div key={text} className="flex items-center gap-3 rounded-2xl bg-white/10 p-4 text-sm font-bold ring-1 ring-white/15"><CheckCircle2 className="h-5 w-5 shrink-0"/>{text}</div>)}</div></div></section>

    <Section eyebrow="Results & visibility" title="Know What Happened With Every Campaign" subtitle="Use clear status and activity views to understand what progressed and what needs review."><AnalyticsMockup /></Section>

    <section className="px-4 py-8 sm:px-6"><div className="mx-auto max-w-7xl rounded-[2.25rem] border border-blue-100 bg-white p-7 shadow-sm sm:p-10 lg:p-14"><div className="mx-auto max-w-3xl text-center"><Pill>How delivery works</Pill><h2 className="mt-5 text-3xl font-black tracking-tight sm:text-4xl">Delivered Through the Web, Not Traditional Email</h2><p className="mt-4 leading-7 text-slate-600">ContactReachout is designed around website contact-form outreach. Instead of relying entirely on email infrastructure and inbox placement, your message is submitted through the target company’s website contact workflow.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-2"><FlowCard featured title="ContactReachout" icon={Globe2} items={['Your Lead','Target Website','Contact Form','Message Submission','Company Contact Workflow']}/><FlowCard title="Traditional Cold Email" icon={Mail} items={['Your Lead','Email Infrastructure','Sending Domain / Mailbox','Email Delivery','Inbox / Promotions / Spam']}/></div><DeliveryComparison /><div className="mt-8 rounded-3xl bg-blue-50 p-6"><h3 className="text-xl font-black">Why This Matters</h3><p className="mt-2 text-sm leading-7 text-slate-600">Traditional cold email depends on an email delivery chain before a prospect can see your message. ContactReachout takes a different approach by submitting outreach through the target company’s website contact form, creating an additional website-based channel for B2B outreach.</p></div></div></section>

    <Section eyebrow="Built for teams" title="A focused workspace for modern outreach teams"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{audiences.map(([Icon,title,text])=><FeatureCard key={title} icon={Icon} title={title} text={text}/>)}</div></Section>

    <section className="px-4 pb-16 pt-8 sm:px-6"><div className="mx-auto max-w-7xl rounded-[2.25rem] bg-[#0e6de4] p-8 text-center text-white shadow-xl shadow-blue-200/60 sm:p-12"><h2 className="text-3xl font-black sm:text-4xl">Ready to Reach More Clients Without More Manual Outreach?</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-blue-100">Upload your leads, personalize your messages with AI, submit through website contact forms, and manage your outreach from one workspace.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href="/signup" className="rounded-xl bg-white px-6 py-3 text-sm font-black text-[#0e6de4]">Start Free</Link><Link href="/pricing" className="rounded-xl border border-white/30 bg-white/10 px-6 py-3 text-sm font-black text-white">View Pricing</Link></div></div></section>
  </main><LandingFooter /></div>;
}

function Section({eyebrow,title,subtitle,children}:{eyebrow:string;title:string;subtitle?:string;children:React.ReactNode}){return <section className="px-4 py-8 sm:px-6"><div className="mx-auto max-w-7xl rounded-[2.25rem] border border-blue-100 bg-white p-7 shadow-sm sm:p-10 lg:p-14"><div className="mx-auto mb-10 max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[.18em] text-[#0e6de4]">{eyebrow}</p><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">{title}</h2>{subtitle&&<p className="mt-4 leading-7 text-slate-600">{subtitle}</p>}</div>{children}</div></section>}
function Pill({children}:{children:React.ReactNode}){return <span className="inline-flex rounded-full border border-blue-200 bg-blue-50 px-4 py-2 text-xs font-black text-[#0e6de4]">{children}</span>}
function Primary({href,children}:{href:string;children:React.ReactNode}){return <Link href={href} className="inline-flex items-center gap-2 rounded-xl bg-[#0e6de4] px-6 py-3.5 text-sm font-black text-white shadow-lg shadow-blue-200">{children}<ArrowRight className="h-4 w-4"/></Link>}
function Secondary({href,children}:{href:string;children:React.ReactNode}){return <Link href={href} className="rounded-xl border border-slate-200 bg-white px-6 py-3.5 text-sm font-black text-slate-800">{children}</Link>}
function FeatureCard({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <article className="rounded-3xl border border-slate-200 bg-slate-50/60 p-6 transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-[#0e6de4]"><Icon className="h-6 w-6"/></span><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>}
function CampaignMockup(){return <div className="rounded-[2rem] border border-blue-100 bg-[#f4f8fd] p-5 shadow-xl"><div className="flex items-center justify-between"><div><p className="text-xs font-black text-[#0e6de4]">CAMPAIGN PREVIEW</p><p className="mt-1 font-black">Website Outreach — Demo</p></div><span className="rounded-full bg-blue-100 px-3 py-1 text-[10px] font-black text-blue-700">DEMO DATA</span></div><div className="mt-5 grid grid-cols-2 gap-3">{[['Forms Found','2,480'],['Messages Personalized','2,310'],['Submitted','2,180'],['Replies','126']].map(([label,value])=><div key={label} className="rounded-2xl bg-white p-4 shadow-sm"><p className="text-2xl font-black">{value}</p><p className="mt-1 text-xs font-bold text-slate-500">{label}</p></div>)}</div><div className="mt-4 space-y-2">{['Upload lead list','Find contact forms','Personalize messages','Review and submit'].map((text,index)=><div key={text} className="flex items-center gap-3 rounded-xl bg-white p-3 text-xs font-bold"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#0e6de4] text-white">{index+1}</span>{text}<CheckCircle2 className="ml-auto h-4 w-4 text-emerald-500"/></div>)}</div></div>}
function MessageCard({label,title,text,featured=false}:{label:string;title:string;text:string;featured?:boolean}){return <article className={`rounded-3xl border p-7 ${featured?'border-blue-300 bg-blue-50 shadow-lg shadow-blue-100':'border-slate-200 bg-slate-50'}`}><div className="flex items-center justify-between"><span className={`rounded-full px-3 py-1 text-[10px] font-black ${featured?'bg-[#0e6de4] text-white':'bg-slate-200 text-slate-600'}`}>{label}</span>{featured&&<span className="flex items-center gap-1 text-xs font-black text-[#0e6de4]"><Sparkles className="h-4 w-4"/>Personalized with AI</span>}</div><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-4 rounded-2xl bg-white p-5 text-sm leading-7 text-slate-600 shadow-sm">{text}</p></article>}
const comparisonRows=[['Delivery Channel','Email inbox','Website contact form'],['Email Infrastructure','Sending domains and mailboxes may be required','Website-based outreach workflow'],['Personalization','Manual or automated email personalization','AI-powered contact-form personalization'],['Workflow','Email campaigns','Website contact-form campaigns'],['Tracking','Email campaign metrics','Submission and campaign tracking'],['Lead Requirement','Email-focused lists','Website and lead data']];
function ComparisonTable(){return <div className="overflow-hidden rounded-3xl border border-slate-200"><div className="grid grid-cols-[.8fr_1fr_1fr] bg-slate-50 p-4 text-xs font-black sm:text-sm"><span>Comparison</span><span>Traditional Cold Email</span><span className="text-[#0e6de4]">ContactReachout</span></div>{comparisonRows.map(row=><div key={row[0]} className="grid grid-cols-[.8fr_1fr_1fr] gap-3 border-t border-slate-100 p-4 text-xs leading-5 sm:text-sm"><strong>{row[0]}</strong><span className="text-slate-500">{row[1]}</span><span className="font-semibold text-slate-800">{row[2]}</span></div>)}</div>}
function FlowCard({title,icon:Icon,items,featured=false}:{title:string;icon:any;items:string[];featured?:boolean}){return <article className={`rounded-3xl border p-7 ${featured?'border-blue-300 bg-blue-50':'border-slate-200 bg-slate-50'}`}><div className="flex items-center gap-3"><span className={`rounded-xl p-3 ${featured?'bg-[#0e6de4] text-white':'bg-white text-slate-600'}`}><Icon className="h-5 w-5"/></span><h3 className="text-xl font-black">{title}</h3></div><div className="mt-6 space-y-2">{items.map((item,index)=><div key={item}><div className="rounded-xl bg-white p-3 text-center text-sm font-bold shadow-sm">{item}</div>{index<items.length-1&&<ArrowRight className="mx-auto my-1 h-4 w-4 rotate-90 text-blue-400"/>}</div>)}</div></article>}
function AnalyticsMockup(){return <div className="rounded-3xl border border-blue-100 bg-[#f4f8fd] p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-black">Campaign Results — Demo UI</h3><span className="rounded-full bg-blue-100 px-3 py-1 text-[10px] font-black text-blue-700">EXAMPLE DATA</span></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{['Forms Found','Messages Generated','Messages Submitted','Successful','Failed','Credits Used'].map((label,index)=><div key={label} className="rounded-2xl bg-white p-4 shadow-sm"><p className="text-xl font-black">{[480,452,421,389,32,842][index]}</p><p className="mt-1 text-[11px] font-bold text-slate-500">{label}</p></div>)}</div><div className="mt-5 overflow-hidden rounded-2xl bg-white">{[['Atlas Partners','Submitted'],['Northstar Labs','Processing'],['Greenfield Co.','Completed'],['Harbor Systems','Failed']].map(([company,status])=><div key={company} className="flex items-center justify-between border-b border-slate-100 p-4 text-sm"><span className="font-bold">{company}</span><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-black text-blue-700">{status}</span></div>)}</div></div>}
function DeliveryComparison(){const data=[['Delivery Layer','Target website contact form','Email delivery infrastructure'],['Primary Outreach Asset','Website / company contact form','Email address'],['Infrastructure Dependency','Website-based outreach workflow','Sending domains, mailboxes and authentication'],['Personalization','AI-powered message personalization','Email personalization']];return <div className="mt-6 grid gap-4 md:grid-cols-2">{data.map(([title,ours,email])=><article key={title} className="rounded-2xl border border-slate-200 p-5"><h3 className="font-black">{title}</h3><p className="mt-3 text-sm"><strong className="text-[#0e6de4]">ContactReachout:</strong> {ours}</p><p className="mt-2 text-sm text-slate-500"><strong>Traditional Email:</strong> {email}</p></article>)}</div>}
