'use client';

import React, { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Bot, CheckCircle2, Loader2, RefreshCw, Save, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import type { Lead, LeadList } from '@/types';

type ReviewStatus = 'Not Reviewed' | 'Reviewed' | 'Edited' | 'Approved';
interface StoredCampaign { id: string; name: string; selectedListId?: string; prospectsList?: Lead[]; aiInstructions?: string; aiPersonalizationEnabled?: boolean; aiPersonalizedMessages?: Record<string, string>; aiMessageStatuses?: Record<string, ReviewStatus>; [key: string]: unknown }
interface Draft { leadId: string; companyName: string; body: string; originalBody: string; status: ReviewStatus; error?: string }
const goals = ['Generate Interest', 'Book a Meeting', 'Introduce a Service', 'Request a Call', 'Custom'];
const tones = ['Professional', 'Friendly', 'Conversational', 'Direct'];

export default function AiPersonalizationClient() {
  const [sourceType, setSourceType] = useState<'campaign' | 'list'>('campaign');
  const [campaigns, setCampaigns] = useState<StoredCampaign[]>([]);
  const [leadLists, setLeadLists] = useState<LeadList[]>([]);
  const [allLeads, setAllLeads] = useState<Lead[]>([]);
  const [sourceId, setSourceId] = useState('');
  const [offer, setOffer] = useState('');
  const [goal, setGoal] = useState('Generate Interest');
  const [customGoal, setCustomGoal] = useState('');
  const [tone, setTone] = useState('Professional');
  const [length, setLength] = useState<'Short' | 'Medium' | 'Custom'>('Medium');
  const [customLength, setCustomLength] = useState('');
  const [instructions, setInstructions] = useState('Mention relevant verified context. Keep the message natural and end with a simple question.');
  const [drafts, setDrafts] = useState<Draft[]>([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [busy, setBusy] = useState(false);
  const [progress, setProgress] = useState('');
  const [notice, setNotice] = useState('');

  useEffect(() => { try { const stored = JSON.parse(localStorage.getItem('user_campaigns') || '[]'); setCampaigns(stored); setLeadLists(JSON.parse(localStorage.getItem('user_lead_lists') || '[]')); setAllLeads(JSON.parse(localStorage.getItem('user_imported_leads') || '[]')); const requested = new URLSearchParams(location.search).get('campaign'); if (requested && stored.some((item: StoredCampaign) => item.id === requested)) setSourceId(requested); } catch { setNotice('Saved campaign data could not be loaded from this browser.'); } }, []);
  const selectedCampaign = useMemo(() => campaigns.find(item => item.id === sourceId), [campaigns, sourceId]);
  const selectedLeads = useMemo(() => !sourceId ? [] : sourceType === 'campaign' ? selectedCampaign?.prospectsList || [] : allLeads.filter(lead => lead.listId === sourceId), [allLeads, selectedCampaign, sourceId, sourceType]);
  useEffect(() => { setDrafts([]); setCurrentIndex(0); setNotice(''); if (selectedCampaign?.aiInstructions) setInstructions(selectedCampaign.aiInstructions); }, [selectedCampaign, sourceId]);

  const generateForLead = async (lead: Lead) => {
    const maxWords = length === 'Short' ? 60 : length === 'Medium' ? 120 : Number(customLength.match(/\d+/)?.[0]) || 120;
    const response = await fetch('/api/ai/personalize', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ companyName: lead.companyName, websiteUrl: lead.website, industry: lead.industry, location: [lead.city, lead.state, lead.country].filter(Boolean).join(', '), contactPersonName: [lead.firstName, lead.lastName].filter(Boolean).join(' '), offer, messageGoal: goal === 'Custom' ? customGoal : goal, tone, maxWords, customInstructions: instructions, campaignInstructions: customLength, leadFields: { firstName: lead.firstName, lastName: lead.lastName, jobTitle: lead.title, companyName: lead.companyName, industry: lead.industry, location: [lead.city, lead.state, lead.country].filter(Boolean).join(', ') } }) });
    const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Generation failed.'); return data.body as string;
  };
  const generateAll = async () => { if (!selectedLeads.length || !offer.trim()) { setNotice('Select prospects and describe what you are offering.'); return; } setBusy(true); setNotice(''); const generated: Draft[] = []; for (let index = 0; index < selectedLeads.length; index++) { const lead = selectedLeads[index]; setProgress(`Generating ${index + 1} of ${selectedLeads.length}`); try { const body = await generateForLead(lead); generated.push({ leadId: lead.id, companyName: lead.companyName, body, originalBody: body, status: 'Not Reviewed' }); } catch(error) { generated.push({ leadId: lead.id, companyName: lead.companyName, body: '', originalBody: '', status: 'Not Reviewed', error: error instanceof Error ? error.message : 'Generation failed.' }); } setDrafts([...generated]); } setBusy(false); setProgress(''); setCurrentIndex(0); setNotice(`${generated.filter(item => !item.error).length} of ${generated.length} messages generated. Failed items can be retried.`); };
  const updateDraft = (updates: Partial<Draft>) => setDrafts(current => current.map((item, index) => index === currentIndex ? {...item, ...updates} : item));
  const regenerate = async () => { const lead = selectedLeads.find(item => item.id === drafts[currentIndex]?.leadId); if (!lead) return; if (drafts[currentIndex].status === 'Edited' && !confirm('Regenerate and replace your manual edit?')) return; setBusy(true); try { const body = await generateForLead(lead); updateDraft({ body, originalBody: body, status: 'Not Reviewed', error: undefined }); } catch(error) { updateDraft({ error: error instanceof Error ? error.message : 'Generation failed.' }); } finally { setBusy(false); } };
  const save = () => { const approved = drafts.filter(item => item.status === 'Approved'); if (approved.length !== drafts.length || !drafts.length) { setNotice('Approve every personalized message before continuing to the campaign.'); return; } const map = Object.fromEntries(approved.map(item => [item.leadId, item.body])); const statuses = Object.fromEntries(approved.map(item => [item.leadId, item.status])); if (sourceType === 'campaign' && selectedCampaign) { const updated = campaigns.map(campaign => campaign.id === selectedCampaign.id ? {...campaign, aiPersonalizationEnabled:true, aiInstructions:instructions, aiPersonalizedMessages:map, aiMessageStatuses:statuses, prospectsList:(campaign.prospectsList || []).map(lead => map[lead.id] ? {...lead, personalizedOpeningLine:map[lead.id]} : lead)} : campaign); localStorage.setItem('user_campaigns', JSON.stringify(updated)); setCampaigns(updated); } else { const updated = allLeads.map(lead => map[lead.id] ? {...lead, personalizedOpeningLine:map[lead.id]} : lead); localStorage.setItem('user_imported_leads', JSON.stringify(updated)); setAllLeads(updated); } setNotice('All approved messages were saved. The campaign will use these final edited versions.'); };
  const current = drafts[currentIndex]; const lead = selectedLeads.find(item => item.id === current?.leadId); const reviewed = drafts.filter(item => item.status !== 'Not Reviewed').length;

  return <div className="mx-auto max-w-6xl space-y-6 pb-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black text-[#0e6de4]">Controlled personalization workflow</p><h1 className="mt-1 text-3xl font-black text-slate-950">AI Personalization</h1><p className="mt-2 text-sm text-slate-600">Configure → generate → review one by one → edit → approve → start campaign.</p></div><Link href={sourceId ? `/campaigns/new?edit=${sourceId}` : '/campaigns/new'} className="rounded-xl border border-blue-200 bg-white px-4 py-2.5 text-sm font-black text-[#0e6de4]">Open campaign</Link></div>
    <div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section className="space-y-5 rounded-3xl border border-blue-100 bg-white p-6 shadow-sm"><Step title="1. Select prospects"><div className="grid grid-cols-2 gap-2 rounded-xl bg-blue-50 p-1">{(['campaign','list'] as const).map(type => <button key={type} onClick={() => {setSourceType(type);setSourceId('')}} className={`rounded-lg px-3 py-2 text-xs font-black ${sourceType === type ? 'bg-[#0e6de4] text-white' : 'text-slate-600'}`}>{type === 'campaign' ? 'Campaign' : 'Lead List'}</button>)}</div><select value={sourceId} onChange={e => setSourceId(e.target.value)} className="w-full rounded-xl border border-blue-100 px-3 py-3 text-sm font-semibold"><option value="">Select source</option>{(sourceType === 'campaign' ? campaigns : leadLists).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><p className="rounded-xl bg-blue-50 p-3 text-sm font-bold text-blue-800">{selectedLeads.length} prospects selected</p></Step><Step title="2. What are you offering?"><textarea rows={5} value={offer} onChange={e => setOffer(e.target.value)} placeholder="Describe the product or service you want to promote…" className="w-full rounded-xl border border-blue-100 p-3 text-sm" /></Step><Step title="3. Message settings"><Field label="Message Goal"><select value={goal} onChange={e => setGoal(e.target.value)} className="input">{goals.map(item => <option key={item}>{item}</option>)}</select></Field>{goal === 'Custom' && <input value={customGoal} onChange={e => setCustomGoal(e.target.value)} placeholder="Describe the goal" className="input" />}<Field label="Tone"><select value={tone} onChange={e => setTone(e.target.value)} className="input">{tones.map(item => <option key={item}>{item}</option>)}</select></Field><Field label="Length"><select value={length} onChange={e => setLength(e.target.value as typeof length)} className="input"><option>Short</option><option>Medium</option><option>Custom</option></select></Field>{length === 'Custom' && <input value={customLength} onChange={e => setCustomLength(e.target.value)} placeholder="e.g. Keep it under 80 words" className="input" />}</Step><Step title="4. Custom Instructions"><textarea rows={6} value={instructions} onChange={e => setInstructions(e.target.value)} className="w-full rounded-xl border border-blue-100 p-3 text-sm" /></Step><Button onClick={generateAll} disabled={busy || !selectedLeads.length} className="w-full py-3">{busy ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}{progress || 'Generate Personalized Messages'}</Button></section>
      <section className="rounded-3xl border border-blue-100 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black">AI Message Review</h2><p className="text-xs text-slate-500">{drafts.length ? `${reviewed} / ${drafts.length} reviewed` : 'Generate messages to begin'}</p></div>{drafts.length > 0 && <span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-black text-blue-700">Prospect {currentIndex + 1} of {drafts.length}</span>}</div>{notice && <p className="mt-4 rounded-xl border border-blue-100 bg-blue-50 p-3 text-sm font-semibold text-blue-800">{notice}</p>}{current && lead ? <div className="mt-6 space-y-5"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="font-black text-slate-950">{[lead.firstName,lead.lastName].filter(Boolean).join(' ') || lead.companyName}</p><p className="mt-1 text-sm text-slate-600">{[lead.title,lead.companyName].filter(Boolean).join(' · ')}</p><p className="mt-1 text-xs text-[#0e6de4]">{lead.website}</p></div>{current.error && <p className="rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{current.error}</p>}<label className="block text-sm font-black text-slate-700">AI Personalized Message<textarea rows={14} value={current.body} onChange={e => updateDraft({body:e.target.value,status:'Edited'})} onBlur={() => current.status === 'Not Reviewed' && updateDraft({status:'Reviewed'})} className="mt-2 w-full rounded-2xl border border-blue-100 p-4 text-sm leading-7 outline-none focus:border-[#0e6de4]" /></label><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={regenerate} disabled={busy}><RefreshCw className="mr-2 h-4 w-4" />Regenerate</Button><Button variant="outline" onClick={() => updateDraft({status: current.status === 'Edited' ? 'Edited' : 'Reviewed'})}><Save className="mr-2 h-4 w-4" />Save Changes</Button><Button onClick={() => updateDraft({status:'Approved'})}><CheckCircle2 className="mr-2 h-4 w-4" />Approve</Button></div><div className="flex items-center justify-between border-t border-slate-100 pt-5"><Button variant="outline" disabled={currentIndex === 0} onClick={() => setCurrentIndex(i => i-1)}><ArrowLeft className="mr-2 h-4 w-4" />Previous</Button><span className="text-xs font-black text-[#0e6de4]">{current.status}</span><Button variant="outline" disabled={currentIndex === drafts.length-1} onClick={() => setCurrentIndex(i => i+1)}>Next<ArrowRight className="ml-2 h-4 w-4" /></Button></div><Button onClick={save} disabled={!drafts.length} className="w-full py-3"><Bot className="mr-2 h-4 w-4" />Save approved messages to campaign</Button></div> : <div className="mt-6 grid min-h-[520px] place-items-center rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-8 text-center text-sm text-slate-500">Your individually generated prospect messages will appear here.</div>}</section></div></div>;
}

function Step({ title, children }: { title: string; children: React.ReactNode }) { return <div className="space-y-3"><h2 className="font-black text-slate-950">{title}</h2>{children}</div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-bold text-slate-600"><span className="mb-1 block">{label}</span>{children}</label>; }
