import Link from 'next/link';
import { ArrowRight, Bot, CircleHelp, CreditCard, FileSearch, Gift, LifeBuoy, ListChecks, Megaphone, Search, Send, Settings, Upload, UserCircle, Wrench } from 'lucide-react';
import { LandingHeader } from '@/components/layout/LandingHeader';
import { LandingFooter } from '@/components/layout/LandingFooter';

const categories = [
  [CircleHelp,'Getting Started','Create an account, access your dashboard, and prepare your first campaign.'],
  [Megaphone,'Campaigns','Create, edit, save drafts, start campaigns, and monitor progress.'],
  [ListChecks,'Lead Lists','Import, organize, and select prospect or company lead lists.'],
  [Bot,'AI Personalization','Generate relevant messages and review or edit them before submission.'],
  [FileSearch,'Contact Form Submission','Understand form discovery and website-based submission outcomes.'],
  [CreditCard,'Credits & Billing','Review your balance, usage history, and available credit options.'],
  [UserCircle,'Account & Profile','Manage your personal profile and account information.'],
  [Gift,'Referrals','Find your unique referral code and review referral rewards.'],
] as const;
const steps=[['Create Your Account','Create your ContactReachout account and access your dashboard.'],['Add Your Leads','Import your prospect or company list.'],['Create a Campaign','Select your leads and configure your campaign.'],['Find Contact Forms','Identify relevant website contact forms for your prospects.'],['Personalize With AI','Generate messages from available prospect and company information.'],['Review & Submit','Review your messages before starting the submission workflow.'],['Track Results','Monitor campaign progress, submissions, and results.']];
const faqs=[
  ['What is ContactReachout?','ContactReachout is a workspace for organizing bulk website contact-form outreach, AI-assisted personalization, campaigns, and results.'],
  ['How does website contact-form outreach work?','A campaign uses website and lead data to identify available contact forms, prepare messages, and record each submission outcome.'],
  ['How does AI personalization work?','Available prospect and company context is used to draft a more relevant message. You should review the result before submission.'],
  ['Can I edit AI-generated messages before submitting them?','Yes. Review and edit generated content in the campaign workflow before you start submissions.'],
  ['Can I save a campaign as a draft?','Yes. Use Save Draft in the campaign editor when you are not ready to start.'],
  ['How do I import leads?','Use Import Leads File in the dashboard header, then map and confirm the spreadsheet columns.'],
  ['How are credits used?','Eligible form submissions and optional AI personalization use credits according to the pricing rules shown in the application.'],
  ['Where can I purchase additional credits?','Open Billing & Credits from the dashboard sidebar or visit the Pricing page.'],
  ['Can I pause or manage a campaign?','Available campaign actions appear on the Campaigns page and depend on the campaign’s current status.'],
  ['Where can I see my submission results?','Open Results & Review or Usage & History from your dashboard.'],
  ['How do I update my profile?','Open Profile under Account in the dashboard sidebar.'],
  ['How do I contact support?','Use the Contact Support button below to send a message to the ContactReachout team.'],
];
const issues=[['Campaign Not Starting','Check campaign status, selected leads, available credits, and required campaign information.'],['Lead List Issues','Check the file format, required fields, column mapping, and whether the import completed.'],['AI Personalization Issues','Check the selected campaign or lead list and your personalization instructions.'],['Submission Issues','Review campaign results and status to identify failed, blocked, unavailable, or review-required submissions.'],['Credit Issues','Check the current balance and usage history before starting a campaign.'],['Login & Account Issues','Use the available login options or contact support if you cannot access your account.']];

export default function HelpPage(){return <div className="min-h-screen bg-[#f4f8fd] text-slate-950"><LandingHeader/><main>
  <section className="px-4 py-14 text-center sm:px-6 lg:py-20"><div className="mx-auto max-w-3xl"><span className="inline-flex rounded-2xl bg-blue-100 p-3 text-[#0e6de4]"><LifeBuoy className="h-7 w-7"/></span><h1 className="mt-5 text-4xl font-black tracking-tight sm:text-6xl">How Can We Help?</h1><p className="mx-auto mt-5 max-w-2xl leading-8 text-slate-600">Find answers, learn how ContactReachout works, or get help with your account, campaigns, AI personalization, contact-form submissions, and billing.</p><div className="mx-auto mt-8 flex max-w-2xl items-center gap-3 rounded-2xl border border-blue-100 bg-white px-5 py-4 text-left shadow-sm"><Search className="h-5 w-5 text-[#0e6de4]"/><span className="text-sm text-slate-400">Search Help & Support</span><span className="ml-auto rounded-lg bg-slate-100 px-2 py-1 text-[10px] font-black text-slate-500">Browse below</span></div></div></section>
  <HelpSection eyebrow="Browse help" title="Help Categories"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{categories.map(([Icon,title,text])=><article key={title} className="rounded-3xl border border-slate-200 bg-slate-50/70 p-6 transition hover:-translate-y-1 hover:border-blue-200 hover:bg-white hover:shadow-lg"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-50 text-[#0e6de4]"><Icon className="h-5 w-5"/></span><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></HelpSection>
  <HelpSection eyebrow="Quick start" title="Getting Started Guide"><div className="grid gap-3 lg:grid-cols-7">{steps.map(([title,text],index)=><article key={title} className="relative rounded-3xl border border-blue-100 bg-blue-50/50 p-5"><span className="text-xs font-black text-[#0e6de4]">0{index+1}</span><h3 className="mt-3 text-sm font-black">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-600">{text}</p>{index<6&&<ArrowRight className="absolute -right-4 top-1/2 z-10 hidden h-5 w-5 text-blue-400 lg:block"/>}</article>)}</div></HelpSection>
  <HelpSection eyebrow="Common questions" title="Frequently Asked Questions"><div className="mx-auto max-w-4xl space-y-3">{faqs.map(([question,answer],index)=><details key={question} className="group rounded-2xl border border-slate-200 bg-white p-5 open:border-blue-200 open:shadow-sm" open={index===0}><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-black">{question}<span className="text-xl text-[#0e6de4] group-open:rotate-45">+</span></summary><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-600">{answer}</p></details>)}</div></HelpSection>
  <HelpSection eyebrow="Troubleshooting" title="Common Issues"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{issues.map(([title,text])=><article key={title} className="rounded-3xl border border-slate-200 bg-slate-50 p-6"><Wrench className="h-5 w-5 text-[#0e6de4]"/><h3 className="mt-4 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></HelpSection>
  <section className="px-4 pb-16 pt-8 sm:px-6"><div className="mx-auto max-w-7xl rounded-[2rem] bg-[#0e6de4] p-9 text-center text-white sm:p-12"><h2 className="text-3xl font-black">Still Need Help?</h2><p className="mx-auto mt-3 max-w-2xl text-blue-100">Our support team is here to help with ContactReachout, your account, campaigns, AI personalization, submissions, and billing.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href="/contact" className="rounded-xl bg-white px-6 py-3 text-sm font-black text-[#0e6de4]">Contact Support</Link><Link href="/dashboard" className="rounded-xl border border-white/30 bg-white/10 px-6 py-3 text-sm font-black text-white">Go to Dashboard</Link></div></div></section>
  </main><LandingFooter/></div>}

function HelpSection({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <section className="px-4 py-8 sm:px-6"><div className="mx-auto max-w-7xl rounded-[2rem] border border-blue-100 bg-white p-7 shadow-sm sm:p-10"><div className="mb-8"><p className="text-xs font-black uppercase tracking-[.18em] text-[#0e6de4]">{eyebrow}</p><h2 className="mt-3 text-3xl font-black">{title}</h2></div>{children}</div></section>}
