import {
  Campaign,
  DashboardMetrics,
  Lead,
  MessageTemplate,
  ProcessingJob,
  SubmissionResult,
  SystemLog,
} from '@/types';

export const mockMetrics: DashboardMetrics = {
  totalCampaigns: 8,
  totalWebsites: 1420,
  pending: 340,
  processing: 15,
  successful: 820,
  failed: 45,
  reviewRequired: 120,
  blocked: 80,
  successRate: 88.5,
  avgDurationSec: 8.4,
};

export const mockCampaigns: Campaign[] = [
  {
    id: 'cmp-1',
    name: 'Q3 Enterprise SaaS Outreach',
    status: 'running',
    isDryRun: true,
    messageTemplateId: 'tpl-1',
    messageTemplateName: 'Partnership Inquiry v1',
    totalLeads: 500,
    processedLeads: 320,
    successfulCount: 260,
    reviewRequiredCount: 42,
    blockedCount: 12,
    failedCount: 6,
    rateLimitPerMinute: 12,
    maxConcurrency: 5,
    startedAt: '2026-08-11T12:00:00Z',
    createdAt: '2026-08-10T15:30:00Z',
  },
  {
    id: 'cmp-2',
    name: 'Logistics & Supply Chain Tier-1',
    status: 'completed',
    isDryRun: true,
    messageTemplateId: 'tpl-2',
    messageTemplateName: 'Vendor Collaboration v2',
    totalLeads: 450,
    processedLeads: 450,
    successfulCount: 390,
    reviewRequiredCount: 38,
    blockedCount: 15,
    failedCount: 7,
    rateLimitPerMinute: 10,
    maxConcurrency: 4,
    startedAt: '2026-08-09T09:00:00Z',
    completedAt: '2026-08-09T18:30:00Z',
    createdAt: '2026-08-08T11:00:00Z',
  },
  {
    id: 'cmp-3',
    name: 'FinTech Growth Partners (Live Mode)',
    status: 'paused',
    isDryRun: false,
    messageTemplateId: 'tpl-1',
    messageTemplateName: 'Partnership Inquiry v1',
    totalLeads: 250,
    processedLeads: 80,
    successfulCount: 68,
    reviewRequiredCount: 8,
    blockedCount: 3,
    failedCount: 1,
    rateLimitPerMinute: 8,
    maxConcurrency: 3,
    startedAt: '2026-08-11T08:00:00Z',
    createdAt: '2026-08-11T07:15:00Z',
  },
  {
    id: 'cmp-4',
    name: 'Healthcare Tech Inquiries (Draft)',
    status: 'draft',
    isDryRun: true,
    totalLeads: 220,
    processedLeads: 0,
    successfulCount: 0,
    reviewRequiredCount: 0,
    blockedCount: 0,
    failedCount: 0,
    rateLimitPerMinute: 10,
    maxConcurrency: 5,
    createdAt: '2026-08-11T13:45:00Z',
  },
];

export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    domain: 'stripe.com',
    website: 'https://stripe.com',
    companyName: 'Stripe, Inc.',
    firstName: 'Patrick',
    lastName: 'Collison',
    email: 'contact@stripe.com',
    phone: '+1 888-926-2289',
    industry: 'Financial Services',
    city: 'San Francisco',
    country: 'United States',
    status: 'DRY_RUN_COMPLETED',
    contactPageUrl: 'https://stripe.com/contact/sales',
    formConfidence: 98,
    lastAttemptAt: '2026-08-11T14:10:00Z',
    createdAt: '2026-08-10T15:30:00Z',
  },
  {
    id: 'lead-2',
    domain: 'cloudflare.com',
    website: 'https://cloudflare.com',
    companyName: 'Cloudflare',
    firstName: 'Matthew',
    lastName: 'Prince',
    email: 'inquiry@cloudflare.com',
    phone: '+1 888-993-4732',
    industry: 'Cybersecurity',
    city: 'Austin',
    country: 'United States',
    status: 'REVIEW_REQUIRED',
    contactPageUrl: 'https://cloudflare.com/plans/enterprise/contact',
    formConfidence: 92,
    errorCode: 'ERR_CAPTCHA_DETECTED',
    errorMessage: 'Cloudflare Turnstile challenge identified on form container.',
    lastAttemptAt: '2026-08-11T14:12:30Z',
    createdAt: '2026-08-10T15:30:00Z',
  },
  {
    id: 'lead-3',
    domain: 'linear.app',
    website: 'https://linear.app',
    companyName: 'Linear',
    firstName: 'Karri',
    lastName: 'Saarinen',
    email: 'support@linear.app',
    industry: 'Productivity Software',
    city: 'San Francisco',
    country: 'United States',
    status: 'SUBMITTED',
    contactPageUrl: 'https://linear.app/contact',
    formConfidence: 95,
    lastAttemptAt: '2026-08-11T14:15:00Z',
    createdAt: '2026-08-10T15:30:00Z',
  },
  {
    id: 'lead-4',
    domain: 'notion.so',
    website: 'https://notion.so',
    companyName: 'Notion Labs',
    firstName: 'Ivan',
    lastName: 'Zhao',
    email: 'sales@makenotion.com',
    industry: 'Workspace Software',
    city: 'San Francisco',
    country: 'United States',
    status: 'PROCESSING',
    contactPageUrl: 'https://notion.so/contact-sales',
    formConfidence: 90,
    lastAttemptAt: '2026-08-11T14:20:00Z',
    createdAt: '2026-08-10T15:30:00Z',
  },
  {
    id: 'lead-5',
    domain: 'forbidden-site.org',
    website: 'https://forbidden-site.org',
    companyName: 'Restricted Corp',
    firstName: 'John',
    lastName: 'Doe',
    email: 'admin@forbidden-site.org',
    industry: 'Manufacturing',
    status: 'BLOCKED',
    errorCode: 'ERR_ACCESS_DENIED_BOT_BLOCKED',
    errorMessage: 'Target server returned HTTP 403 Forbidden with Bot Protection header.',
    lastAttemptAt: '2026-08-11T13:50:00Z',
    createdAt: '2026-08-10T15:30:00Z',
  },
  {
    id: 'lead-6',
    domain: 'techcorp-demo.com',
    website: 'https://techcorp-demo.com',
    companyName: 'TechCorp Solutions',
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily@techcorp-demo.com',
    industry: 'IT Services',
    status: 'PENDING',
    createdAt: '2026-08-11T14:00:00Z',
  },
];

export const mockTemplates: MessageTemplate[] = [
  {
    id: 'tpl-1',
    name: 'Partnership Inquiry v1',
    subjectTemplate: '{Partnership|Collaboration} with {{company_name}}',
    bodyTemplate:
      '{Hi|Hello|Dear} {{first_name}},\n\nI came across {{company_name}} and was really impressed by your work in {{industry}}. We help companies in {{city}} streamline their B2B client acquisition workflows.\n\nWould you be open to a brief 10-minute introductory call next week?\n\nBest regards,\nAlex Rivera',
    complianceFooter:
      'Sent by Outreach Systems Corp, 500 Market St, San Francisco, CA. Reply with STOP to opt out.',
    isSpintaxEnabled: true,
    variables: ['company_name', 'first_name', 'industry', 'city'],
    createdAt: '2026-08-08T10:00:00Z',
    updatedAt: '2026-08-10T14:20:00Z',
  },
  {
    id: 'tpl-2',
    name: 'Vendor Collaboration v2',
    subjectTemplate: 'Exploring vendor synergies with {{company_name}}',
    bodyTemplate:
      'Hello {{first_name}},\n\nWe are expanding our vendor network in {{country}} and would love to connect with {{company_name}} regarding upcoming opportunities in {{industry}}.\n\nLet me know who on your team is best to discuss this with.\n\nThanks,\nTaylor Smith',
    complianceFooter:
      'Sent by Outreach Systems Corp, 500 Market St, San Francisco, CA. Reply with STOP to opt out.',
    isSpintaxEnabled: false,
    variables: ['first_name', 'country', 'company_name', 'industry'],
    createdAt: '2026-08-09T11:30:00Z',
    updatedAt: '2026-08-09T11:30:00Z',
  },
];

export const mockProcessingJobs: ProcessingJob[] = [
  {
    id: 'job-101',
    campaignId: 'cmp-1',
    campaignName: 'Q3 Enterprise SaaS Outreach',
    leadId: 'lead-4',
    domain: 'notion.so',
    website: 'https://notion.so',
    companyName: 'Notion Labs',
    currentStep: 'SIMULATING_INPUTS',
    progressPercent: 70,
    status: 'active',
    isDryRun: true,
    startedAt: '2026-08-11T14:20:10Z',
    durationMs: 4200,
  },
  {
    id: 'job-102',
    campaignId: 'cmp-1',
    campaignName: 'Q3 Enterprise SaaS Outreach',
    leadId: 'lead-6',
    domain: 'techcorp-demo.com',
    website: 'https://techcorp-demo.com',
    companyName: 'TechCorp Solutions',
    currentStep: 'DISCOVERING_CONTACT_PAGE',
    progressPercent: 25,
    status: 'active',
    isDryRun: true,
    startedAt: '2026-08-11T14:20:12Z',
    durationMs: 2100,
  },
  {
    id: 'job-103',
    campaignId: 'cmp-1',
    campaignName: 'Q3 Enterprise SaaS Outreach',
    leadId: 'lead-7',
    domain: 'airtable.com',
    website: 'https://airtable.com',
    companyName: 'Airtable',
    currentStep: 'WAITING_IN_QUEUE',
    progressPercent: 0,
    status: 'waiting',
    isDryRun: true,
    startedAt: '2026-08-11T14:20:14Z',
    durationMs: 0,
  },
];

export const mockResults: SubmissionResult[] = [
  {
    id: 'res-1',
    campaignId: 'cmp-1',
    campaignName: 'Q3 Enterprise SaaS Outreach',
    leadId: 'lead-1',
    companyName: 'Stripe, Inc.',
    domain: 'stripe.com',
    website: 'https://stripe.com',
    contactPageUrl: 'https://stripe.com/contact/sales',
    status: 'DRY_RUN_SUCCESS',
    leadStatus: 'DRY_RUN_COMPLETED',
    isDryRun: true,
    preSubmitScreenshotUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80',
    submittedAt: '2026-08-11T14:10:00Z',
  },
  {
    id: 'res-2',
    campaignId: 'cmp-1',
    campaignName: 'Q3 Enterprise SaaS Outreach',
    leadId: 'lead-2',
    companyName: 'Cloudflare',
    domain: 'cloudflare.com',
    website: 'https://cloudflare.com',
    contactPageUrl: 'https://cloudflare.com/plans/enterprise/contact',
    status: 'CAPTCHA_TRIGGERED',
    leadStatus: 'REVIEW_REQUIRED',
    isDryRun: true,
    errorCode: 'ERR_CAPTCHA_DETECTED',
    errorMessage: 'Cloudflare Turnstile challenge identified on form container.',
    preSubmitScreenshotUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80',
    submittedAt: '2026-08-11T14:12:30Z',
  },
  {
    id: 'res-3',
    campaignId: 'cmp-3',
    campaignName: 'FinTech Growth Partners (Live Mode)',
    leadId: 'lead-3',
    companyName: 'Linear',
    domain: 'linear.app',
    website: 'https://linear.app',
    contactPageUrl: 'https://linear.app/contact',
    status: 'SUCCESS',
    leadStatus: 'SUBMITTED',
    isDryRun: false,
    httpStatus: 200,
    preSubmitScreenshotUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80',
    postSubmitScreenshotUrl: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&auto=format&fit=crop&q=80',
    submittedAt: '2026-08-11T14:15:00Z',
  },
  {
    id: 'res-4',
    campaignId: 'cmp-1',
    campaignName: 'Q3 Enterprise SaaS Outreach',
    leadId: 'lead-5',
    companyName: 'Restricted Corp',
    domain: 'forbidden-site.org',
    website: 'https://forbidden-site.org',
    contactPageUrl: 'https://forbidden-site.org/contact',
    status: 'BLOCKED_403_429',
    leadStatus: 'BLOCKED',
    isDryRun: true,
    errorCode: 'ERR_ACCESS_DENIED_BOT_BLOCKED',
    errorMessage: 'Target server returned HTTP 403 Forbidden with Bot Protection header.',
    submittedAt: '2026-08-11T13:50:00Z',
  },
];

export const mockLogs: SystemLog[] = [
  {
    id: 'log-1',
    traceId: 'tr-c7a8b41e-5d2f',
    campaignId: 'cmp-1',
    leadId: 'lead-1',
    domain: 'stripe.com',
    step: 'PAGE_NAVIGATION',
    level: 'info',
    message: 'Successfully loaded https://stripe.com in 1420ms (HTTP 200).',
    timestamp: '2026-08-11T14:09:50Z',
  },
  {
    id: 'log-2',
    traceId: 'tr-c7a8b41e-5d2f',
    campaignId: 'cmp-1',
    leadId: 'lead-1',
    domain: 'stripe.com',
    step: 'LINK_DISCOVERY',
    level: 'info',
    message: 'Discovered contact link /contact/sales from homepage navigation bar.',
    timestamp: '2026-08-11T14:09:52Z',
  },
  {
    id: 'log-3',
    traceId: 'tr-c7a8b41e-5d2f',
    campaignId: 'cmp-1',
    leadId: 'lead-1',
    domain: 'stripe.com',
    step: 'FORM_DETECTION',
    level: 'info',
    message: 'Form form#contact-sales detected with confidence score 98. No honeypots detected.',
    timestamp: '2026-08-11T14:09:55Z',
  },
  {
    id: 'log-4',
    traceId: 'tr-c7a8b41e-5d2f',
    campaignId: 'cmp-1',
    leadId: 'lead-1',
    domain: 'stripe.com',
    step: 'SIMULATE_FILL',
    level: 'info',
    message: 'Dry-Run Mode: Successfully populated 6 fields. Captured pre-submit screenshot.',
    timestamp: '2026-08-11T14:10:00Z',
  },
  {
    id: 'log-5',
    traceId: 'tr-99b8214a-11ce',
    campaignId: 'cmp-1',
    leadId: 'lead-2',
    domain: 'cloudflare.com',
    step: 'BOT_DETECTION',
    level: 'warn',
    message: 'Cloudflare Turnstile challenge detected. Aborting interaction and dispatching to manual review queue per compliance policy.',
    timestamp: '2026-08-11T14:12:30Z',
  },
];
